name: flutter_screen_recording_web
description: A new Flutter plugin for record the screen. This plugin can be used for record the screen on android, iOS, and web devices.
version: 1.0.10
homepage: "https://github.com/Isvisoft/flutter_screen_recording"

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screen_recording_platform_interface:
    git:
      url: https://github.com/vvalladolidIV/flutter_screen_recording.git
      path: flutter_screen_recording_platform_interface
      ref: web-v
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.2
  platform_detect: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_screen_recording: ^1.0.10

flutter:
  plugin:
    platforms:
      web:
        pluginClass: WebFlutterScreenRecording
        fileName: flutter_screen_recording_web.dart
